---
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.3.0
      hooks:
          - id: trailing-whitespace
          - id: check-toml
    - repo: https://github.com/ambv/black
      rev: 22.3.0
      hooks:
          - id: black
    - repo: https://github.com/myint/autoflake
      rev: v1.4
      hooks:
          - id: autoflake
            args: [--in-place, --remove-all-unused-imports]
    - repo: https://github.com/PyCQA/isort
      rev: 5.10.1
      hooks:
          - id: isort
            args: [-m, '3', --tc, --profile, black]
