---
version: '2.2'
services:
    postgres:
        restart: always
        image: postgres:12.4
        volumes:
            - pgdata:/var/lib/postgresql/data
        ports:
            - 5432:5432
volumes:
    pgdata:
        driver: local
