"""Create solutions table

Revision ID: 18e69de4cc76
Revises: a3fe450d0d7d
Create Date: 2022-08-04 16:20:29.666794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18e69de4cc76'
down_revision = 'a3fe450d0d7d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
