"""Fix score storage

Revision ID: 3bc5cc274be0
Revises: 7cb0a6e0fdc2
Create Date: 2022-08-04 17:37:05.987915

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3bc5cc274be0'
down_revision = '7cb0a6e0fdc2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('solutions', sa.Column('scores', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.drop_column('solutions', 'answers')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('solutions', sa.Column('answers', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('solutions', 'scores')
    # ### end Alembic commands ###
