"""Rename solution table

Revision ID: b8a0039077de
Revises: 3bc5cc274be0
Create Date: 2022-08-04 18:32:16.822776

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b8a0039077de'
down_revision = '3bc5cc274be0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solution',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('quiz', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('scores', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['quiz'], ['quiz.id'], ),
    sa.ForeignKeyConstraint(['user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('solutions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solutions',
    sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('user', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.Column('quiz', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.Column('scores', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['quiz'], ['quiz.id'], name='solutions_quiz_fkey'),
    sa.ForeignKeyConstraint(['user'], ['user.id'], name='solutions_user_fkey'),
    sa.PrimaryKeyConstraint('id', name='solutions_pkey')
    )
    op.drop_table('solution')
    # ### end Alembic commands ###
