"""Rename question name

Revision ID: e89288485c17
Revises: f050aac5b4c5
Create Date: 2022-08-04 13:41:30.086534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e89288485c17'
down_revision = 'f050aac5b4c5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('question', sa.Text(), nullable=False))
    op.drop_column('question', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('question', 'question')
    # ### end Alembic commands ###
