"""Create quiz, question and answer tables

Revision ID: ead54c9b3828
Revises: 771c311adcf1
Create Date: 2022-08-04 12:11:04.825212

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ead54c9b3828'
down_revision = 'ebc008adeff0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('answer',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('question',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('correct_answer', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('type', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['correct_answer'], ['answer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quiz',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('owner', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['owner'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quiz')
    op.drop_table('question')
    op.drop_table('answer')
    # ### end Alembic commands ###
